from setuptools import find_packages, setup

setup(
    name="ark",
    version="0.1.0",
    description="Spatial Analog Abstraction",
    packages=find_packages(),
    install_requires=[
        "scipy>=1.15.2",
        "matplotlib>=3.7.1",
        "numpy>=2.1.3",
        "pySMT>=0.9.5",
        "tqdm>=4.65.0",
        "sympy>=1.12",
        "palettable>=3.3.3",
        "pylatexenc>=2.10",
        "graphviz>=0.20.1",
        "jax>=0.5.3",
        "optax>=0.1.9",
        "equinox>=0.11.12",
        "jaxtyping>=0.3.1",
        "diffrax>=0.7.0",
        "networkx>=3.3",
        "interpax>=0.3.7",
        "optax>=0.1.7",
        "wandb>=0.19.9",
        "torch>=2.3.1",
        "torchvision>=0.18.1",
    ],
)
